backend:
  name: github
  repo: sunya9/unsweets.log
  branch: master

media_folder: source/images/

collections:
- name: "blog" # Used in routes, e.g. /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "source/_posts" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime", default: ""}
    - {label: "Categories", name: "categories", widget: "list", default: ""}
    - {label: "Author", name: "author", widget: "string", default: "_X_y_z_"}
    - {label: "Content", name: "body", widget: "markdown"}
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  meta:
    # # some entries has empty tags
    - {label: "Tags", name: "tags", widget: "list", default: "" }

publish_mode: editorial_workflow
